export const ACT_GET_ALL_CLIENT = "ACT_GET_ALL_CLIENT";
export const ACT_GET_ALL_CLIENT_FAILED = "ACT_GET_ALL_CLIENT_FAILED";
export const ACT_GET_ALL_CLIENT_SUCCESS = "ACT_GET_ALL_CLIENT_SUCCESS";

export const ACT_CREATE_CLIENT = "ACT_CREATE_CLIENT";
export const ACT_CREATE_CLIENT_FAILED = "ACT_CREATE_CLIENT_FAILED";
export const ACT_CREATE_CLIENT_SUCCESS = "ACT_CREATE_CLIENT_SUCCESS";

export const ACT_UPDATE_CLIENT = "ACT_UPDATE_CLIENT";
export const ACT_UPDATE_CLIENT_FAILED = "ACT_UPDATE_CLIENT_FAILED";
export const ACT_UPDATE_CLIENT_SUCCESS = "ACT_UPDATE_CLIENT_SUCCESS";

export const ACT_GET_CLIENT_DETAIL = "ACT_GET_CLIENT_DETAIL";
export const ACT_GET_CLIENT_DETAIL_FAILED = "ACT_GET_CLIENT_DETAIL_FAILED";
export const ACT_GET_CLIENT_DETAIL_SUCCESS = "ACT_GET_CLIENT_DETAIL_SUCCESS";
