export const GET_IN_OUT_AMOUNT_OF_YEAR = "GET_IN_OUT_AMOUNT_OF_YEAR";
export const GET_IN_OUT_AMOUNT_OF_YEAR_FAILED =
  "GET_IN_OUT_AMOUNT_OF_YEAR_FAILED";
export const GET_IN_OUT_AMOUNT_OF_YEAR_SUCCESS =
  "GET_IN_OUT_AMOUNT_OF_YEAR_SUCCESS";

export const GET_NEW_CLIENT_OF_YEAR = "GET_NEW_CLIENT_OF_YEAR";
export const GET_NEW_CLIENT_OF_YEAR_FAILED = "GET_NEW_CLIENT_OF_YEAR_FAILED";
export const GET_NEW_CLIENT_OF_YEAR_SUCCESS = "GET_NEW_CLIENT_OF_YEAR_SUCCESS";
