export const GET_STATISTIC_OF_MONTH = "GET_STATISTIC_OF_MONTH";
export const GET_STATISTIC_OF_MONTH_FAILED = "GET_STATISTIC_OF_MONTH_FAILED";
export const GET_STATISTIC_OF_MONTH_SUCCESS = "GET_STATISTIC_OF_MONTH_SUCCESS";

export const GET_STATISTIC_OF_YEAR = "GET_STATISTIC_OF_YEAR";
export const GET_STATISTIC_OF_YEAR_FAILED = "GET_STATISTIC_OF_YEAR_FAILED";
export const GET_STATISTIC_OF_YEAR_SUCCESS = "GET_STATISTIC_OF_YEAR_SUCCESS";
