export const ACT_FETCH_LIST_CLIENT = "ACT_FETCH_LIST_CLIENT";
export const ACT_FETCH_LIST_CLIENT_FAILED = "ACT_FETCH_LIST_CLIENT_FAILED";
export const ACT_FETCH_LIST_CLIENT_NO_CONTENT =
  "ACT_FETCH_LIST_CLIENT_NO_CONTENT";
export const ACT_FETCH_LIST_CLIENT_SUCCESS = "ACT_FETCH_LIST_CLIENT_SUCCESS";

export const ACT_CREATE_CLIENT = "ACT_CREATE_CLIENT";
export const ACT_CREATE_CLIENT_FAILED = "ACT_CREATE_CLIENT_FAILED";
export const ACT_CREATE_CLIENT_SUCCESS = "ACT_CREATE_CLIENT_SUCCESS";

export const ACT_LOAD_MORE_CLIENT = "ACT_LOAD_MORE_CLIENT";
export const ACT_LOAD_MORE_CLIENT_FAILED = "ACT_LOAD_MORE_CLIENT_FAILED";
export const ACT_LOAD_MORE_CLIENT_SUCCESS = "ACT_LOAD_MORE_CLIENT_SUCCESS";
