export const ACT_CREATE_ORDER = "ACT_CREATE_ORDER";
export const ACT_CREATE_ORDER_FAILED = "ACT_CREATE_ORDER_FAILED";
export const ACT_CREATE_ORDER_SUCCESS = "ACT_CREATE_ORDER_SUCCESS";

export const ACT_SEARCH_BY_CLIENT_ID = "ACT_SEARCH_BY_CLIENT_ID";
export const ACT_SEARCH_BY_CLIENT_ID_NO_CONTENT =
  "ACT_SEARCH_BY_CLIENT_ID_NO_CONTENT";
export const ACT_SEARCH_BY_CLIENT_ID_FAILED = "ACT_SEARCH_BY_CLIENT_ID_FAILED";
export const ACT_SEARCH_BY_CLIENT_ID_SUCCESS =
  "ACT_SEARCH_BY_CLIENT_ID_SUCCESS";

export const ACT_FETCH_LIST_ORDER = "ACT_FETCH_LIST_ORDER";
export const ACT_FETCH_LIST_ORDER_FAILED = "ACT_FETCH_LIST_ORDER_FAILED";
export const ACT_FETCH_LIST_ORDER_NO_CONTENT =
  "ACT_FETCH_LIST_ORDER_NO_CONTENT";
export const ACT_FETCH_LIST_ORDER_SUCCESS = "ACT_FETCH_LIST_ORDER_SUCCESS";

export const ACT_GET_ORDER_DETAIL = "ACT_GET_ORDER_DETAIL";
export const ACT_GET_ORDER_DETAIL_SUCCESS = "ACT_GET_ORDER_DETAIL_SUCCESS";
export const ACT_GET_ORDER_DETAIL_FAILED = "ACT_GET_ORDER_DETAIL_FAILED";

export const ACT_DO_TRANSACTION = "ACT_DO_TRANSACTION";
export const ACT_DO_TRANSACTION_FAILED = "ACT_DO_TRANSACTION_FAILED";
export const ACT_DO_TRANSACTION_SUCCESS = "ACT_DO_TRANSACTION_SUCCESS";

export const ACT_CONFIRM_CREATE_ORDER_SUCCESS =
  "ACT_CONFIRM_CREATE_ORDER_SUCCESS";

export const GET_TRANSACTION_INCOME_OF_ORDER =
  "GET_TRANSACTION_INCOME_OF_ORDER";
export const GET_TRANSACTION_INCOME_OF_ORDER_FAILED =
  "GET_TRANSACTION_INCOME_OF_ORDER_FAILED";
export const GET_TRANSACTION_INCOME_OF_ORDER_NO_CONTENT =
  "GET_TRANSACTION_INCOME_OF_ORDER_NO_CONTENT";
export const GET_TRANSACTION_INCOME_OF_ORDER_SUCCESS =
  "GET_TRANSACTION_INCOME_OF_ORDER_SUCCESS";
