export const ACT_CREATE_ORDER = "ACT_CREATE_ORDER";
export const ACT_CREATE_ORDER_FAILED = "ACT_CREATE_ORDER_FAILED";
export const ACT_CREATE_ORDER_SUCCESS = "ACT_CREATE_ORDER_SUCCESS";

export const GET_ORDER_OF_CLIENT = "GET_ORDER_OF_CLIENT";
export const GET_ORDER_OF_CLIENT_FAILED = "GET_ORDER_OF_CLIENT_FAILED";
export const GET_ORDER_OF_CLIENT_NO_CONTENT = "GET_ORDER_OF_CLIENT_NO_CONTENT";
export const GET_ORDER_OF_CLIENT_SUCCESS = "GET_ORDER_OF_CLIENT_SUCCESS";

export const ACT_FETCH_LIST_ORDER = "ACT_FETCH_LIST_ORDER";
export const ACT_FETCH_LIST_ORDER_FAILED = "ACT_FETCH_LIST_ORDER_FAILED";
export const ACT_FETCH_LIST_ORDER_NO_CONTENT =
  "ACT_FETCH_LIST_ORDER_NO_CONTENT";
export const ACT_FETCH_LIST_ORDER_SUCCESS = "ACT_FETCH_LIST_ORDER_SUCCESS";

export const LOAD_MORE_LIST_ORDER = "LOAD_MORE_LIST_ORDER";
export const LOAD_MORE_LIST_ORDER_FAILED = "LOAD_MORE_LIST_ORDER_FAILED";
export const LOAD_MORE_LIST_ORDER_SUCCESS = "LOAD_MORE_LIST_ORDER_SUCCESS";

export const ACT_GET_ORDER_DETAIL = "ACT_GET_ORDER_DETAIL";
export const ACT_GET_ORDER_DETAIL_SUCCESS = "ACT_GET_ORDER_DETAIL_SUCCESS";
export const ACT_GET_ORDER_DETAIL_FAILED = "ACT_GET_ORDER_DETAIL_FAILED";

export const ACT_DO_TRANSACTION = "ACT_DO_TRANSACTION";
export const ACT_DO_TRANSACTION_FAILED = "ACT_DO_TRANSACTION_FAILED";
export const ACT_DO_TRANSACTION_SUCCESS = "ACT_DO_TRANSACTION_SUCCESS";

export const ACT_CONFIRM_CREATE_ORDER_SUCCESS =
  "ACT_CONFIRM_CREATE_ORDER_SUCCESS";

export const GET_TRANSACTION_INCOME_OF_ORDER =
  "GET_TRANSACTION_INCOME_OF_ORDER";
export const GET_TRANSACTION_INCOME_OF_ORDER_FAILED =
  "GET_TRANSACTION_INCOME_OF_ORDER_FAILED";
export const GET_TRANSACTION_INCOME_OF_ORDER_NO_CONTENT =
  "GET_TRANSACTION_INCOME_OF_ORDER_NO_CONTENT";
export const GET_TRANSACTION_INCOME_OF_ORDER_SUCCESS =
  "GET_TRANSACTION_INCOME_OF_ORDER_SUCCESS";

export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_REQUEST_FAILED = "UPDATE_CLIENT_REQUEST_FAILED";
export const UPDATE_CLIENT_REQUEST_SUCCESS = "UPDATE_CLIENT_REQUEST_SUCCESS";
