export const ACT_GET_ALL_USER = "ACT_GET_ALL_USER";
export const ACT_GET_ALL_USER_FAILED = "ACT_GET_ALL_USER_FAILED";
export const ACT_GET_ALL_USER_SUCCESS = "ACT_GET_ALL_USER_SUCCESS";

export const ACT_CREATE_USER = "ACT_CREATE_USER";
export const ACT_CREATE_USER_FAILED = "ACT_CREATE_USER_FAILED";
export const ACT_CREATE_USER_SUCCESS = "ACT_CREATE_USER_SUCCESS";

export const ACT_GET_USER_DETAIL = "ACT_GET_USER_DETAIL";
export const ACT_GET_USER_DETAIL_FAILED = "ACT_GET_USER_DETAIL_FAILED";
export const ACT_GET_USER_DETAIL_SUCCESS = "ACT_GET_USER_DETAIL_SUCCESS";

export const ACT_UPDATE_USER = "ACT_UPDATE_USER";
export const ACT_UPDATE_USER_FAILED = "ACT_UPDATE_USER_FAILED";
export const ACT_UPDATE_USER_SUCCESS = "ACT_UPDATE_USER_SUCCESS";

export const ACT_SHOW_UPDATE_USER = "ACT_SHOW_UPDATE_USER";

export const ACT_DELETE_USER = "ACT_DELETE_USER";
export const ACT_DELETE_USER_FAILED = "ACT_DELETE_USER_FAILED";
export const ACT_DELETE_USER_SUCCESS = "ACT_DELETE_USER_SUCCESS";

export const ACT_RESET_USER_PASS = "ACT_RESET_USER_PASS";
export const ACT_RESET_USER_PASS_FAILED = "ACT_RESET_USER_PASS_FAILED";
export const ACT_RESET_USER_PASS_SUCCESS = "ACT_RESET_USER_PASS_SUCCESS";
