export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";
export const GET_NOTIFICATION_NO_CONTENT = "GET_NOTIFICATION_NO_CONTENT";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";

export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const REMOVE_NOTIFICATION_FAILED = "REMOVE_NOTIFICATION_FAILED";
export const REMOVE_NOTIFICATION_SUCCESS = "REMOVE_NOTIFICATION_SUCCESS";
