export const GET_ALL_CLIENT = "GET_ALL_CLIENT";
export const GET_ALL_CLIENT_FAILED = "GET_ALL_CLIENT_FAILED";
export const GET_ALL_CLIENT_NO_CONTENT = "GET_ALL_CLIENT_NO_CONTENT";
export const GET_ALL_CLIENT_SUCCESS = "GET_ALL_CLIENT_SUCCESS";

export const LOAD_MORE_CLIENT = "LOAD_MORE_CLIENT";
export const LOAD_MORE_CLIENT_FAILED = "LOAD_MORE_CLIENT_FAILED";
export const LOAD_MORE_CLIENT_SUCCESS = "LOAD_MORE_CLIENT_SUCCESS";
