export const GET_NOTIFICATION_ACCOUNTANT = "GET_NOTIFICATION_ACCOUNTANT";
export const GET_NOTIFICATION_ACCOUNTANT_FAILED =
  "GET_NOTIFICATION_ACCOUNTANT_FAILED";
export const GET_NOTIFICATION_ACCOUNTANT_SUCCESS =
  "GET_NOTIFICATION_ACCOUNTANT_SUCCESS";
