export const ACT_GET_ALL_ORDER = "ACT_GET_ALL_ORDER";
export const ACT_GET_ALL_ORDER_FAILED = "ACT_GET_ALL_ORDER_FAILED";
export const ACT_GET_ALL_ORDER_SUCCESS = "ACT_GET_ALL_ORDER_SUCCESS";

export const ACT_CREATE_ORDER = "ACT_CREATE_ORDER";
export const ACT_CREATE_ORDER_FAILED = "ACT_CREATE_ORDER_FAILED";
export const ACT_CREATE_ORDER_SUCCESS = "ACT_CREATE_ORDER_SUCCESS";

export const ACT_REMOVE_NEW_ORDER = "ACT_REMOVE_NEW_ORDER";

export const ACT_GET_ORDER_DETAIL = "ACT_GET_ORDER_DETAIL";
export const ACT_GET_ORDER_DETAIL_SUCCESS = "ACT_GET_ORDER_DETAIL_SUCCESS";
export const ACT_GET_ORDER_DETAIL_FAILED = "ACT_GET_ORDER_DETAIL_FAILED";

export const ACT_UPDATE_ORDER = "ACT_UPDATE_ORDER";
export const ACT_UPDATE_ORDER_FAILED = "ACT_UPDATE_ORDER_FAILED";
export const ACT_UPDATE_ORDER_SUCCESS = "ACT_UPDATE_ORDER_SUCCESS";

export const ACT_PAYMENT_ORDER = "ACT_PAYMENT_ORDER";
export const ACT_PAYMENT_ORDER_FAILED = "ACT_PAYMENT_ORDER_FAILED";
export const ACT_PAYMENT_ORDER_SUCCESS = "ACT_PAYMENT_ORDER_SUCCESS";
