export const GET_TRANSACTION_OF_CLIENT = "GET_TRANSACTION_OF_CLIENT";
export const GET_TRANSACTION_OF_CLIENT_FALIED =
  "GET_TRANSACTION_OF_CLIENT_FALIED";
export const GET_TRANSACTION_OF_CLIENT_SUCCESS =
  "GET_TRANSACTION_OF_CLIENT_SUCCESS";

export const CREATE_ALL_TRANSACTION = "CREATE_ALL_TRANSACTION";
export const CREATE_ALL_TRANSACTION_FAILED = "CREATE_ALL_TRANSACTION_FAILED";
export const CREATE_ALL_TRANSACTION_SUCCESS = "CREATE_ALL_TRANSACTION_SUCCESS";
export const CREATE_ALL_TRANSACTION_CONFIRM = "CREATE_ALL_TRANSACTION_CONFIRM";

export const SEARCH_TRANSACTION = "SEARCH_TRANSACTION";
export const SEARCH_TRANSACTION_FAILED = "SEARCH_TRANSACTION_FAILED";
export const SEARCH_TRANSACTION_NO_CONTENT = "SEARCH_TRANSACTION_NO_CONTENT";
export const SEARCH_TRANSACTION_SUCCESS = "SEARCH_TRANSACTION_SUCCESS";

export const LOAD_MORE_SEARCH_TRANSACTION = "LOAD_MORE_SEARCH_TRANSACTION";
export const LOAD_MORE_SEARCH_TRANSACTION_FAILED =
  "LOAD_MORE_SEARCH_TRANSACTION_FAILED";
export const LOAD_MORE_SEARCH_TRANSACTION_SUCCESS =
  "LOAD_MORE_SEARCH_TRANSACTION_SUCCESS";

export const LOAD_MORE_CLIENT_TRANSACTION_LIST =
  "LOAD_MORE_CLIENT_TRANSACTION_LIST";
export const LOAD_MORE_CLIENT_TRANSACTION_LIST_FAILED =
  "LOAD_MORE_CLIENT_TRANSACTION_LIST_FAILED";
export const LOAD_MORE_CLIENT_TRANSACTION_LIST_SUCCESS =
  "LOAD_MORE_CLIENT_TRANSACTION_LIST_SUCCESS";

export const GET_TRANSACTION_NEED_VALIDATE = "GET_TRANSACTION_NEED_VALIDATE";
export const GET_TRANSACTION_NEED_VALIDATE_FAILED =
  "GET_TRANSACTION_NEED_VALIDATE_FAILED";
export const GET_TRANSACTION_NEED_VALIDATE_NO_CONTENT =
  "GET_TRANSACTION_NEED_VALIDATE_NO_CONTENT";
export const GET_TRANSACTION_NEED_VALIDATE_SUCCESS =
  "GET_TRANSACTION_NEED_VALIDATE_SUCCESS";

export const LOAD_MORE_TRANSACTION_NEED_VALIDATE =
  "LOAD_MORE_TRANSACTION_NEED_VALIDATE";
export const LOAD_MORE_TRANSACTION_NEED_VALIDATE_FAILED =
  "LOAD_MORE_TRANSACTION_NEED_VALIDATE_FAILED";
export const LOAD_MORE_TRANSACTION_NEED_VALIDATE_SUCCESS =
  "LOAD_MORE_TRANSACTION_NEED_VALIDATE_SUCCESS";

export const VALIDATE_TRANSACTION_OK = "VALIDATE_TRANSACTION_OK";
export const VALIDATE_TRANSACTION_OK_FAILED = "VALIDATE_TRANSACTION_OK_FAILED";
export const VALIDATE_TRANSACTION_OK_SUCCESS =
  "VALIDATE_TRANSACTION_OK_SUCCESS";
