export const FETCH_TRANSACTION_PROJECT = "FETCH_TRANSACTION_PROJECT";
export const FETCH_TRANSACTION_PROJECT_FAILED =
  "FETCH_TRANSACTION_PROJECT_FAILED";
export const FETCH_TRANSACTION_PROJECT_SUCCESS =
  "FETCH_TRANSACTION_PROJECT_SUCCESS";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";

export const SAVE_ALL_TRANSACTION = "SAVE_ALL_TRANSACTION";
export const SAVE_ALL_TRANSACTION_FAILED = "SAVE_ALL_TRANSACTION_FAILED";
export const SAVE_ALL_TRANSACTION_SUCCESS = "SAVE_ALL_TRANSACTION_SUCCESS";
