export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_FAILED = "GET_ALL_USER_FAILED";
export const GET_ALL_USER_NO_CONTENT = "GET_ALL_USER_NO_CONTENT";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";

export const LOAD_MORE_LIST_USER = "LOAD_MORE_LIST_USER";
export const LOAD_MORE_LIST_USER_FAILED = "LOAD_MORE_LIST_USER_FAILED";
export const LOAD_MORE_LIST_USER_SUCCESS = "LOAD_MORE_LIST_USER_SUCCESS";

export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_FAILED = "GET_USER_DETAIL_FAILED";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const GET_PASSWORD = "GET_PASSWORD";
export const GET_PASSWORD_FAILED = "GET_PASSWORD_FAILED";
export const GET_PASSWORD_SUCCESS = "GET_PASSWORD_SUCCESS";
