export const ACT_FETCH_USER = "ACT_FETCH_USER";
export const ACT_FETCH_USER_SUCCESS = "ACT_FETCH_USER_SUCCESS";
export const ACT_FETCH_USER_FAILED = "ACT_FETCH_USER_FAILED";
export const ACT_CREATE_USER = "ACT_CREATE_USER";
export const ACT_CREATE_USER_FAILED = "ACT_CREATE_USER_FAILED";
export const ACT_CREATE_USER_SUCCESS = "ACT_CREATE_USER_SUCCESS";
export const ACT_CREATE_PROJECT_FOR_USER = "ACT_CREATE_PROJECT_FOR_USER";
