export const GET_NOTIFICATION_TECHNICIAN = "GET_NOTIFICATION_TECHNICIAN";
export const GET_NOTIFICATION_TECHNICIAN_FAILED =
  "GET_NOTIFICATION_TECHNICIAN_FAILED";
export const GET_NOTIFICATION_TECHNICIAN_SUCCESS =
  "GET_NOTIFICATION_TECHNICIAN_SUCCESS";
