export const GET_LIST_TASK = "GET_LIST_TASK";
export const GET_LIST_TASK_FAILED = "GET_LIST_TASK_FAILED";
export const GET_LIST_TASK_NO_CONTENT = "GET_LIST_TASK_NO_CONTENT";
export const GET_LIST_TASK_SUCCESS = "GET_LIST_TASK_SUCCESS";

export const LOAD_MORE_LIST_TASK = "LOAD_MORE_LIST_TASK";
export const LOAD_MORE_LIST_TASK_FAILED = "LOAD_MORE_LIST_TASK_FAILED";
export const LOAD_MORE_LIST_TASK_SUCCESS = "LOAD_MORE_LIST_TASK_SUCCESS";

export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const GET_TASK_DETAIL_FAILED = "GET_TASK_DETAIL_FAILED";
export const GET_TASK_DETAIL_SUCCESS = "GET_TASK_DETAIL_SUCCESS";

export const UPDATE_PROGRESS = "UPDATE_PROGRESS";
export const UPDATE_PROGRESS_FAILED = "UPDATE_PROGRESS_FAILED";
export const UPDATE_PROGRESS_SUCCESS = "UPDATE_PROGRESS_SUCCESS";

export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const UPDATE_ITEMS_FAILED = "UPDATE_ITEMS_FAILED";
export const UPDATE_ITEMS_SUCCESS = "UPDATE_ITEMS_SUCCESS";
