export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCES = "GET_USER_INFO_SUCCES";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";
export const CREATE_PROJECT_CLEAR = "CREATE_PROJECT_CLEAR";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
export const FETCH_PROJECT_DETAIL = "FETCH_PROJECT_DETAIL";
export const FETCH_PROJECT_DETAIL_SUCCESS = "FETCH_PROJECT_DETAIL_SUCCESS";
export const FETCH_PROJECT_DETAIL_FAILED = "FETCH_PROJECT_DETAIL_FAILED";
export const FETCH_PROJECT_DETAIL_NOT_FOUND = "FETCH_PROJECT_DETAIL_NOT_FOUND";
export const UPDATE_PROJECT_INFO = "UPDATE_PROJECT_INFO";
export const UPDATE_PROJECT_INFO_SUCCESS = "UPDATE_PROJECT_INFO_SUCCESS";
export const UPDATE_PROJECT_INFO_FAILED = "UPDATE_PROJECT_INFO_FAILED";
export const CHANGE_PHASE = "CHANGE_PHASE";
export const CHANGE_PHASE_SUCCESS = "CHANGE_PHASE_SUCCESS";
export const CHANGE_PHASE_FAILED = "CHANGE_PHASE_FAILED";
export const CONFIRM_WORK = "CONFIRM_WORK";
export const CONFIRM_WORK_SUCCESS = "CONFIRM_WORK_SUCCESS";
export const CONFIRM_WORK_FAILED = "CONFIRM_WORK_FAILED";
export const UPDATE_PROJECT_DETAIL = "UPDATE_PROJECT_DETAIL";
export const UPDATE_PROJECT_DETAIL_SUCCESS = "UPDATE_PROJECT_DETAIL_SUCCESS";
export const UPDATE_PROJECT_DETAIL_FAILED = "UPDATE_PROJECT_DETAIL_FAILED";
export const CLOSE_PROJECT = "CLOSE_PROJECT";
export const CLOSE_PROJECT_SUCCESS = "CLOSE_PROJECT_SUCCESS";
export const CLOSE_PROJECT_FAILED = "CLOSE_PROJECT_FAILED";
export const FETCH_LIST_PROJECT = "FETCH_LIST_PROJECT";
export const FETCH_LIST_PROJECT_SUCCESS = "FETCH_LIST_PROJECT_SUCCESS";
export const FETCH_LIST_PROJECT_FAILED = "FETCH_LIST_PROJECT_FAILED";
export const FETCH_LIST_PROJECT_NO_CONTENT = "FETCH_LIST_PROJECT_NO_CONTENT";

export const FETCH_LIST_PROJECT_OF_USER = "FETCH_LIST_PROJECT_OF_USER";
export const FETCH_LIST_PROJECT_OF_USER_SUCCESS =
  "FETCH_LIST_PROJECT_OF_USER_SUCCESS";
export const FETCH_LIST_PROJECT_OF_USER_FAILED =
  "FETCH_LIST_PROJECT_OF_USER_FAILED";
export const FETCH_LIST_PROJECT_OF_USER_NO_CONTENT =
  "FETCH_LIST_PROJECT_OF_USER_NO_CONTENT";
