export const ACT_LOG_OUT = "ACT_LOG_OUT";

export const ACT_AUTHENTICATE = "ACT_AUTHENTICATE";
export const ACT_AUTHENTICATE_SUCCESS = "ACT_AUTHENTICATE_SUCCESS";
export const ACT_AUTHENTICATE_FAILED = "ACT_AUTHENTICATE_FAILED";

export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const VALIDATE_TOKEN_SUCCESS = "VALIDATE_TOKEN_SUCCESS";
export const VALIDATE_TOKEN_FAILED = "VALIDATE_TOKEN_FAILED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
